# Generated by Django 5.1.7 on 2025-03-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_fname_alter_user_gender_alter_user_lname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=200),
        ),
    ]
