# Generated by Django 5.1.7 on 2025-03-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_interests_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.CharField(max_length=1000),
        ),
    ]
