const categorizedInterests = [
  {
    category: "Nature & Adventure",
    interests: [
      "adrenaline & extreme",
      "atv & off-road",
      "balloon rides",
      "ski & snow",
      "kayaking & canoeing",
      "safaris",
      "hiking & camping",
      "mountains",
      "deserts",
      "nature & parks",
      "nature & wildlife",
      "zoos & aquariums",
      "surfing",
      "water sports",
      "waterskiing & jet skiing",
      "beaches",
      "boat  & water sports",
      "bodies of water",
      "windsurfing & kitesurfing",
    ],
  },
  {
    category: "History & Culture",
    interests: [
      "ancient ruins",
      "monuments & statues",
      "museums",
      "points of interest & landmarks",
      "sacred & religious sites",
      "sights & landmarks",
      "historic sites",
      "historical & heritage",
      "history museums",
      "cemeteries",
      "churches & cathedrals",
      "art galleries",
      "art museums",
      "cultural",
      "libraries",
      "archaeology",
    ],
  },
  {
    category: "Shopping & Markets",
    interests: [
      "farmers markets",
      "flea & street markets",
      "gift & specialty shops",
      "antique stores",
      "shopping",
    ],
  },
  {
    category: "Wellness & Nightlife",
    interests: ["nightlife", "spas & wellness"],
  },
  {
    category: "Theme & Water Parks",
    interests: [
      "theme parks",
      "water & amusement parks",
      "swim with dolphins",
      "scuba & snorkeling",
      "shark diving",
      "submarine",
    ],
  },
];

export default categorizedInterests;
